In [2]:
import numpy as np
import pandas as pd

students = [
    "Aarav Sharma", "Vivaan Patel", "Aditya Verma", "Arjun Singh", "Sai Kumar",
    "Krishna Reddy", "Rohan Mehta", "Karan Malhotra", "Rahul Yadav", "Ankit Gupta",
    "Harsh Agarwal", "Mohit Jain", "Siddharth Mishra", "Yash Thakur", "Dev Joshi",
    "Aryan Kapoor", "Shubham Tiwari", "Manish Chauhan", "Nikhil Bansal", "Piyush Saxena",
    "Sneha Iyer", "Ananya Nair", "Priya Sharma", "Neha Verma", "Kavya Reddy",
    "Pooja Singh", "Riya Patel", "Simran Kaur", "Aditi Gupta", "Meera Nair",
    "Ishita Jain", "Tanvi Shah", "Ritika Das", "Swati Mishra", "Nisha Yadav",
    "Komal Agarwal", "Shruti Kulkarni", "Divya Menon", "Payal Saxena", "Sakshi Chauhan",
    "Varun Arora", "Rajat Khanna", "Deepak Pandey", "Amit Dubey", "Saurabh Srivastava",
    "Vikas Choudhary", "Gaurav Tyagi", "Abhishek Tripathi", "Mayank Sinha", "Rakesh Pal"
]

np.random.seed(42)
data = {
    "Math": np.random.randint(50, 100, 50),
    "Science": np.random.randint(50, 100, 50),
    "English": np.random.randint(50, 100, 50),
    "Computer": np.random.randint(50, 100, 50)
}

df = pd.DataFrame(data, index=students)

print(df.head())
print("\nShape of dataset:", df.shape)

              Math  Science  English  Computer
Aarav Sharma    88       51       58        62
Vivaan Patel    78       69       73        81
Aditya Verma    64       77       50        88
Arjun Singh     92       96       93        98
Sai Kumar       57       56       57        81

Shape of dataset: (50, 4)


In [ ]:
#Part A: Vector & Matrix Fundamentals

#1. Represent each student's subject scores as a vector.
vectors = np.array(df)

#2.1 Norm-1 and Norm-2 of vectors.
A = vectors[0]
B = vectors[1]

print("Vector A:", A)
print("Vector B:", B,"\n")

#Norm 1
norm1_A = np.linalg.norm(A, ord=1)
norm1_B = np.linalg.norm(B, ord=1)

print("L1 Norm of A:", norm1_A)
print("L1 Norm of B:", norm1_B,"\n")

#Norm 2
norm2_A = np.linalg.norm(A, ord=2)
norm2_B = np.linalg.norm(B, ord=2)

print("L2 Norm of A:", norm2_A)
print("L2 Norm of B:", norm2_B,"\n")

#2.2 Dot product and angle between two students' score vectors.
dot_product = np.dot(A, B)
print("Dot Product:", dot_product,"\n")

#2.3 Cross product (for 3D selected subjects).
A_3D = A[:3]
B_3D = B[:3]

cross_product = np.cross(A_3D, B_3D)
print("Cross Product:", cross_product,"\n")

#3 Find the projection of one vector onto another.
projection = (dot_product / (norm2_B**2)) * B
print("Projection of A onto B:", projection)


Vector A: [88 51 58 62]
Vector B: [78 69 73 81] 

L1 Norm of A: 259.0
L1 Norm of B: 301.0 

L2 Norm of A: 132.48773528142144
L2 Norm of B: 150.7812985751217 

Dot Product: 19639 

Cross Product: [ -279 -1900  2094] 

Projection of A onto B: [67.37813943 59.60373873 63.05902793 69.96960633]


In [ ]:
#Part B: Matrix Operations

#4.1 Matrix addition and multiplication.

M = np.array(df)
print("Matrix Shape:", M.shape)
print(M[:5],"\n")

#addition
M_add = M + M
print("Matrix Addition:\n", M_add[:5],"\n")

#Multiplication
M_T = M.T
M_mul = np.dot(M, M_T)
print("Matrix Multiplication Shape:", M_mul.shape)

#4.2 Transpose
transpose = M.T
print("Transpose Shape:", transpose.shape,"\n")

#4.3 Determinant
square_matrix = M[:4, :4]
det = np.linalg.det(square_matrix)
print("Square Matrix:\n", square_matrix)
print("Determinant:", det)




Matrix Shape: (50, 4)
[[88 51 58 62]
 [78 69 73 81]
 [64 77 50 88]
 [92 96 93 98]
 [57 56 57 81]] 

Matrix Addition:
 [[176 102 116 124]
 [156 138 146 162]
 [128 154 100 176]
 [184 192 186 196]
 [114 112 114 162]] 

Matrix Multiplication Shape: (50, 50)
Transpose Shape: (4, 50) 

Square Matrix:
 [[88 51 58 62]
 [78 69 73 81]
 [64 77 50 88]
 [92 96 93 98]]
Determinant: 794476.0000000008


Part C: Linear Transformations & Geometry

Que 5: Explain line, plane, and hyperplane with respect to your dataset dimensions.

Ans: (i) A line is 1-dimensional is defined using A point (a) Direction (d), If you take 1 subject only (e.g., Math) → it's a line Example: Only Math scores → students lie on a line.
(ii) A plane is 2-dimensional Formed using 2 features, Math + Science → forms a 2D plane. Each student = a point on that plane.
(iii) Hyperplane is a Extension of plane to higher dimensions 4 subjects → 4D space So students lie in a hyperplane, use in Machine Learning (SVM, classification)

Que 6: Show how dimensionality increases from 2D → 3D → higher dimensions with hyperplanes. 

Ans: As dimensions increase, data moves from a 2D plane to 3D space and then to n-dimensional space, where it is represented by a hyperplane, which generalizes lines and planes to higher dimensions.



In [47]:
#Part D: Eigenvalues & Eigenvectors

#7. Compute the eigenvalues and eigenvectors of the covariance matrix
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors,"\n")

cov_matrix = np.cov(M, rowvar=False)
print("Covariance Matrix:\n", cov_matrix,"\n")

#8. Perform LU Decomposition of the dataset matrix.
from scipy.linalg import lu
P, L, U = lu(square_matrix)
print("L:\n", L)
print("\nU:\n", U)



Eigenvalues:
 [305.80487677  24.62786904 -20.21414361  -5.2186022 ]

Eigenvectors:
 [[ 0.41238074  0.83019493 -0.13236737 -0.14398676]
 [ 0.48850271 -0.13030527 -0.26346141 -0.744345  ]
 [ 0.46174942 -0.3888047   0.87905944  0.23620827]
 [ 0.61489406 -0.37766098 -0.37459506  0.60780258]] 

Covariance Matrix:
 [[192.95673469  -8.09469388  24.06857143  26.98040816]
 [ -8.09469388 228.45755102  -0.92        13.70163265]
 [ 24.06857143  -0.92       204.20244898   6.36489796]
 [ 26.98040816  13.70163265   6.36489796 191.73102041]] 

L:
 [[ 1.          0.          0.          0.        ]
 [ 0.95652174  1.          0.          0.        ]
 [ 0.69565217 -0.25026624  1.          0.        ]
 [ 0.84782609  0.30351438 -0.15808579  1.        ]]

U:
 [[ 92.          96.          93.          98.        ]
 [  0.         -40.82608696 -30.95652174 -31.73913043]
 [  0.           0.         -22.44302449  11.8828541 ]
 [  0.           0.           0.           9.42483629]]


In [36]:
#9. Perform Singular Value Decomposition (SVD) and explain its role in dimensionality reduction

U, S, Vt = np.linalg.svd(M)
print("U:\n", U)
print("\nSingular Values:\n", S)
print("\nV^T:\n", Vt)

U:
 [[-1.22567507e-01 -1.78939268e-01 -1.04367053e-01 ... -1.85000113e-01
  -3.70577743e-02 -1.40922356e-01]
 [-1.42594304e-01 -6.14065943e-02 -5.24725028e-02 ... -3.29836518e-01
   1.11731455e-01 -8.99464328e-02]
 [-1.32504615e-01  1.32937209e-01 -2.18425325e-01 ... -1.10952775e-01
   3.75452340e-02  2.18071048e-01]
 ...
 [-1.44096582e-01 -2.63177957e-01 -2.72917061e-01 ...  8.60642365e-01
   6.71124753e-04 -2.69419853e-02]
 [-1.42312953e-01  4.31644829e-02 -4.96985584e-02 ...  8.73900782e-03
   9.08010042e-01 -3.59976941e-02]
 [-1.39512397e-01 -2.10131844e-01  1.19822889e-01 ... -2.66786435e-02
  -1.48099480e-02  9.29492558e-01]]

Singular Values:
 [1055.78870891  106.77850133   96.72401681   88.07393687]

V^T:
 [[-0.4960617  -0.50124869 -0.49116576 -0.51130102]
 [-0.41670353  0.8268005  -0.37502328 -0.04600696]
 [-0.26373785  0.16474357  0.73079879 -0.60764712]
 [ 0.71464908  0.19496216 -0.28990836 -0.60598647]]


In [42]:
#10. Apply Principal Component Analysis (PCA) to reduce the dataset from multiple subjects to 2 dimensions.

X = df[["Math", "Science", "English", "Computer"]].values

mean = np.mean(X, axis=0)
X_centered = X - mean
cov_matrix = np.cov(X_centered, rowvar=False)
print("Covariance Matrix:\n", cov_matrix,"\n")

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

W = eigenvectors[:, :2]
X_pca = np.dot(X_centered, W)
print("PCA Result (2D):\n", X_pca[:5])

Covariance Matrix:
 [[192.95673469  -8.09469388  24.06857143  26.98040816]
 [ -8.09469388 228.45755102  -0.92        13.70163265]
 [ 24.06857143  -0.92       204.20244898   6.36489796]
 [ 26.98040816  13.70163265   6.36489796 191.73102041]] 

Eigenvalues:
 [158.3054172  190.88780251 235.68926146 232.46527393]

Eigenvectors:
 [[-0.71643962 -0.24893526  0.59285587 -0.27067958]
 [-0.19689373  0.18038658  0.26131116  0.92758289]
 [ 0.28797215  0.74528579  0.5517142  -0.2392333 ]
 [ 0.60416817 -0.59164264  0.52521409  0.09534136]]
PCA Result (2D):
 [[-13.21579263 -23.38735445]
 [  3.81403026  -5.76108042]
 [-11.40839063  11.61885225]
 [ 39.13233726  12.33028057]
 [-20.86041529  -8.30765405]]


In [50]:
# 11 Apply Linear Discriminant Analysis (LDA) to classify students into "Above Average" and "Below Average" categories.

subjects = ["Math", "Science", "English", "Computer"]
df["Average"] = df[subjects].mean(axis=1)
overall_avg = df["Average"].mean()
df["Category"] = df["Average"].apply(lambda x: "Above Average" if x >= overall_avg else "Below Average")
print(df[["Average", "Category"]].head())

              Average       Category
Aarav Sharma    64.75  Below Average
Vivaan Patel    75.25  Above Average
Aditya Verma    69.75  Below Average
Arjun Singh     94.75  Above Average
Sai Kumar       62.75  Below Average
